
import { LibraryDocument } from '@/types';

export const libraryDocuments: LibraryDocument[] = [
  {
    slug: 'constitution-of-bangladesh-en',
    title: 'The Constitution of the People’s Republic of Bangladesh',
    author: 'Government of Bangladesh',
    category: 'Constitution',
    published: '2022-12-16',
    filePath: '/library/constitution-en.pdf',
    thumbnail: 'https://picsum.photos/seed/const1/400/600',
  },
  {
    slug: 'constitution-of-bangladesh-bn',
    title: 'গণপ্রজাতন্ত্রী বাংলাদেশের সংবিধান',
    author: 'গণপ্রজাতন্ত্রী বাংলাদেশ সরকার',
    category: 'Constitution',
    published: '2022-12-16',
    filePath: '/library/constitution-bn.pdf',
    thumbnail: 'https://picsum.photos/seed/const2/400/600',
  },
  {
    slug: 'digital-security-act-2018',
    title: 'ডিজিটাল নিরাপত্তা আইন, ২০১৮',
    author: 'গণপ্রজাতন্ত্রী বাংলাদেশ সরকার',
    category: 'Law & Acts',
    published: '2018-10-08',
    filePath: '/library/digital-security-act-2018.pdf',
    thumbnail: 'https://picsum.photos/seed/dsa/400/600',
  },
  {
    slug: 'cyber-security-act-2023',
    title: 'সাইবার নিরাপত্তা আইন, ২০২৩',
    author: 'গণপ্রজাতন্ত্রী বাংলাদেশ সরকার',
    category: 'Law & Acts',
    published: '2023-09-18',
    filePath: '/library/cyber-security-act-2023.pdf',
    thumbnail: 'https://picsum.photos/seed/csa/400/600',
  },
  {
    slug: 'online-safety-guide',
    title: 'আপনার অনলাইন সুরক্ষা নিশ্চিত করার উপায়',
    author: 'টেক সহাই',
    category: 'Legal Awareness',
    published: '2024-01-15',
    filePath: '/library/online-safety-guide-bn.pdf',
    thumbnail: 'https://picsum.photos/seed/safety/400/600',
  },
  {
    slug: 'land-law-basics',
    title: 'ভূমি আইনের প্রাথমিক ধারণা',
    author: 'ড. আইনুন নিশাত',
    category: 'Books / Publications',
    published: '2023-05-20',
    filePath: '/library/land-law-basics.pdf',
    thumbnail: 'https://picsum.photos/seed/landlaw/400/600',
  },
  {
    slug: 'consumer-rights-guide',
    title: 'ভোক্তা হিসেবে আপনার অধিকার',
    author: 'কনজ্যুমারস অ্যাসোসিয়েশন অব বিডি',
    category: 'Rights & Guidelines',
    published: '2023-03-15',
    filePath: '/library/consumer-rights-guide.pdf',
    thumbnail: 'https://picsum.photos/seed/consumer/400/600',
  },
  {
    slug: 'human-rights-in-bangladesh',
    title: 'মানবাধিকার পরিস্থিতি: বাংলাদেশ',
    author: 'আইন ও সালিশ কেন্দ্র (আসক)',
    category: 'Books / Publications',
    published: '2024-03-01',
    filePath: '/library/human-rights-bangladesh.pdf',
    thumbnail: 'https://picsum.photos/seed/humanrights/400/600',
  },
  {
    slug: 'the-penal-code-1860',
    title: 'দণ্ডবিধি, ১৮৬০',
    author: 'ব্রিটিশ ভারত সরকার',
    category: 'Law & Acts',
    published: '1860-10-06',
    filePath: '/library/penal-code-1860.pdf',
    thumbnail: 'https://picsum.photos/seed/penalcode/400/600',
  },
   {
    slug: 'factfulness',
    title: 'ফ্যাক্টফুলনেস',
    author: 'হ্যান্স রোজলিং',
    category: 'Books / Publications',
    published: '2018-04-03',
    filePath: '/library/human-rights-bangladesh.pdf',
    thumbnail: 'https://picsum.photos/seed/fact/400/600',
  },
];
